name: Metrics
on:
  schedule:
    - cron: "0 0-23/12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          base: header, repositories
          template: classic
          config_timezone: Asia/Saigon

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, tex, less, dockerfile, batchfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_types: commit

          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories

          config_order: base.header, base.repositories, lines, isocalendar, languages, notable, followup
      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.right.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Saigon

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_ignored: html, css, tex, less, dockerfile, batchfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A

          config_order: wakatime, leetcode, topics, achivements